Repository CAU-OSS-project-practice/OSS-file-manager, pull requests merged in 2023-05, with the labels that each got.

#2 [CHORE] 개발환경 세팅 #1
  .gitignore
  files_new.py
  requirements.txt
Labels: CHORE, 규한😎

#10 [FEATURE] View 부분 구현
  data/git_logo.png
  data/img_source/git_logo_source.png
  files_new.py
Labels: CHORE, 우형😎

#11 [FEATURE] 버튼 클릭 시 이벤트 리스너 구현(init, add, commit) #5
  files_new.py
Labels: FEATURE, 규한😎

#15 [FEATURE] 선택한 파일명 변경하기(git mv) #14
  files_new.py
Labels: FEATURE, 규한😎

#16 [FEATURE] Git Status 에 따른 value 표시 기능 구현 FEATURE #12
  files_new.py
Labels: FIX, CHORE, FEATURE, 우형😎

#17 [FEATURE] 버튼 클릭 시 이벤트 리스너 구현(restore, restore --staged)
  files_new.py
Labels: FEATURE

#19 [FIX] git mv 경로 재설정 및 git commit staged 파일 리스트 띄우기 #18
  files_new.py
Labels: FIX, 규한😎

#26 [FEATURE] git status 변수 구현
  files_new.py
Labels: FIX, FEATURE, 우형😎

#28 [FEATURE] #27 - get_relative_repo_path 함수 구현, git add 함수 수정
  files_new.py
Labels: FEATURE, 우형😎

#33 [FEATURE] GIT STATUS에 따른 file icon 표시기능 구현
  data/icon_file_both.png
  data/icon_file_staged.png
  data/icon_file_unstaged.png
  data/icon_folder_both.png
  data/icon_folder_staged.png
  data/icon_folder_unstaged.png
  files_new.py
Labels: FEATURE, 우형😎

#37 [FIX] commit할 때 .git 이 관리하는 서브디렉토리안의 파일들 상태 감지 #36
  files_new.py
Labels: FIX, 규한😎

#44 [FEATURE] #43 - UI for branch features
  files_new.py
Labels: FEATURE, 우형😎

#50 [FEATURE] branch 기능 구현하기 #47
  files_new.py
Labels: FEATURE, 규한😎

#58 [FEATURE] #55 git history graph
  README.md
  files_new.py
  history_graph.py
  license
Labels: FEATURE, 우형😎

#60 [FEATURE] git clone 기능 구현하기 #53
  files_new.py
Labels: FEATURE, 규한😎

#61 [FIX] - #59 FIX GRAPH BUG
  history_graph.py
Labels: FIX, 우형😎

#63 [DESIGN] #62 - reorder UI
  files_new.py
  history_graph.py
Labels: DESIGN, 우형😎

#65 [FEATURE] - #64 Implement Toggle Button
  files_new.py
Labels: FEATURE, 우형😎
